import os
from dotenv import load_dotenv
load_dotenv()
API_KEY = os.getenv("ALPACA_API_KEY")
SECRET_KEY = os.getenv("ALPACA_SECRET_KEY")
BASE_URL = os.getenv("ALPACA_BASE_URL", "https://paper-api.alpaca.markets")
if not API_KEY or not SECRET_KEY:
    raise EnvironmentError("ALPACA_API_KEY and ALPACA_SECRET_KEY must be set in .env")
SPACE_TICKERS = ["RKLB","ASTS","LUNR","KTOS","NOC","LMT"]
TECH_TICKERS = ["NVDA","AMD","MSFT","GOOGL","AVGO","QCOM","INTC","PLTR","TSLA","COIN","IONQ"]
DATACENTER_TICKERS = ["EQIX","DLR","VRT","SMCI","DELL","HPE","GEO"]
HEDGE_TICKERS = ["SQQQ"]
DEFAULT_TICKERS = SPACE_TICKERS + TECH_TICKERS + DATACENTER_TICKERS + HEDGE_TICKERS
MA_SHORT_WINDOW = 10
MA_LONG_WINDOW = 30
RSI_PERIOD = 10
RSI_OVERSOLD = 35
RSI_OVERBOUGHT = 65
STRONG_OVERSOLD = 25
NORMAL_OVERSOLD = 30
WEAK_OVERSOLD = 35
ORDER_FRACTION = 0.07
ORDER_FRACTION_WEAK = 0.05
ORDER_FRACTION_NORMAL = 0.07
ORDER_FRACTION_STRONG = 0.10
TRAILING_STOP_PCT = 4.0
STOP_LOSS_PCT = 0.05
VOLUME_MA_DAYS = 20
SECTOR_ROTATION_DAYS = 5
CAMPAIGN_DAYS = 30
